config/routes.rb
Rails.application.routes.draw do
	resources :images
	get '/', to: 'images#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
require_relative 'imageupload'
class Image < ApplicationRecord
	mount_uploader :image, ImageUploader
end

app/models/imageupload.rb
class ImageUploader < CarrierWave::Uploader::Base
	storage :file
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

	def index
		@images = Image.all
	end

	def show
		@image = Image.find(params[:id])
	end

	def new
		@image = Image.new
	end

	def create
		@image = Image.new(image_params)
		p image_params
		if @image.save
			redirect_to image_path(@image)
		else
			render new_image_path
		end
	end

	private
	def image_params
		params.require(:image).permit(:name, :image)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/index.html.erb
<h2>Image Gallery</h2>
<ul>
	<% @images.each do |image| %>
		<li class="display-list">
			<div>
				<img class="display-index" src="<%= image.image %>" />
			</div>
			<%= link_to image.name, image_path(image) %>
		</li>
	<% end %>
</ul>

app/views/images/new.html.erb
<div class="new-form">
	<%= form_for @image do |f| %>
		<p><%= f.label :name %>: 
	  <%= f.text_field :name %></p>
	  <p><%= f.label :image %>: 
	  <%= f.file_field :image %></p>
	  <p><%= f.submit "Submit" %></p>
	<% end %>
</div>

app/views/images/show.html.erb
<h2><%= @image.name %></h2>
<img src="<%= @image.image %>" />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gallery</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div>
  		<%= link_to "Home", images_path %> | 
  		<%= link_to "Add Image", new_image_path %>
  	</div>
    <%= yield %>
  </body>
</html>